apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatbot-automation
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
